
CREATE COLOR_COUNTERS 0 , 0 , 0 , DOES> SWAP CELLS + ;

1E7 CONSTANT X_SQUARES
210 CONSTANT X_COUNTERS
CREATE Y_COUNTERS 30 , 6F , AE , DOES> SWAP CELLS + @ ;



: REFRESH_LEGEND ( -- )
  BLACK 40 180 200 0 COLOR_RECTANGLE
  R COLOR_COUNTERS @ X_COUNTERS R Y_COUNTERS PRINT
  G COLOR_COUNTERS @ X_COUNTERS G Y_COUNTERS PRINT
  B COLOR_COUNTERS @ X_COUNTERS B Y_COUNTERS PRINT ;


: RESET_COUNTERS ( -- )
  0 R COLOR_COUNTERS !
  0 G COLOR_COUNTERS !
  0 B COLOR_COUNTERS !
  REFRESH_LEGEND ;


: PRINT_LEGEND ( -- )
  RED F F X_SQUARES R Y_COUNTERS COLOR_RECTANGLE
  GREEN F F X_SQUARES G Y_COUNTERS COLOR_RECTANGLE
  BLUE F F X_SQUARES B Y_COUNTERS COLOR_RECTANGLE
  REFRESH_LEGEND ;


: COUNT_COLOR ( -- )
  GET_RGB
  R RGB_COMPONENT @
  G RGB_COMPONENT @
  B RGB_COMPONENT @
  CALCULATE_MAX MAX @
  CASE
  R RGB_COMPONENT @ OF R COLOR_COUNTERS ++ ENDOF
  G RGB_COMPONENT @ OF G COLOR_COUNTERS ++ ENDOF
  B RGB_COMPONENT @ OF B COLOR_COUNTERS ++ ENDOF
  ENDCASE
  REFRESH_LEGEND
  R RGB_COMPONENT @ R CALCULATE_COLOR
  G RGB_COMPONENT @ G CALCULATE_COLOR
  B RGB_COMPONENT @ B CALCULATE_COLOR
  OR OR
  DX COLOR_WINDOW ;
